### ISSUE TITLE
Is there a pip install method?

### ISSUE THREAD

**Issue by wxlearncoding** [mateuszbuda/ml-stat-util#9]
Dear author,

Thank you for sharing your code with us! May I ask is there a pip install method? I haven't used docker before. 

Looking forward to your reply. Thx.

**Comment by mateuszbuda** [comment]
Sorry, there is no pip package created yet. I planned to do this but didn't have time. For now, you can simply copy the https://github.com/mateuszbuda/ml-stat-util/blob/master/stat_util.py file to your project and include requirements from https://github.com/mateuszbuda/ml-stat-util/blob/master/requirements.txt.

**Comment by wxlearncoding** [comment]
Hi,

Thank you for your promote reply. This is a good solution as well. And, I will mark the source and author of this function. Thanks again for sharing.

PS: I tried to install Docker on Windows 10. But, I can not install the Docker Desktop because of the error "docker desktop windows hypervisor is not present". So, I think it will be nice to have pip package. 😁🙏
